apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pds-ehealth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pds-project
  source:
    repoURL: https://github.com/FaresFandouli/ehealth-devops.git
    targetRevision: feature/add-cicd
    path: k8s-gitops
    directory:
      recurse: true
      include: '{base/*.yaml,infrastructure/*.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: pds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
