#!/bin/bash
set -e

# =============================================================================
# Kubernetes Cluster Setup Script
# This script is generated by Terraform and contains the actual IPs
# =============================================================================

MASTER_IP="${master_ip}"
WORKER1_IP="${worker1_ip}"
WORKER2_IP="${worker2_ip}"

echo "==================================================================="
echo "Kubernetes Cluster Setup"
echo "==================================================================="
echo "Master:  $MASTER_IP"
echo "Worker1: $WORKER1_IP"
echo "Worker2: $WORKER2_IP"
echo "==================================================================="

# This script should be run on the MASTER node

echo ""
echo "Step 1: Initialize Kubernetes control-plane on Master"
echo "-------------------------------------------------------------------"

# Initialize the cluster
sudo kubeadm init \
  --pod-network-cidr=10.244.0.0/16 \
  --apiserver-advertise-address=$MASTER_IP \
  --kubernetes-version=v1.31.0

echo ""
echo "Step 2: Configure kubectl for the admin user"
echo "-------------------------------------------------------------------"

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

echo ""
echo "Step 3: Install Calico CNI network plugin"
echo "-------------------------------------------------------------------"

kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml

echo ""
echo "Step 4: Wait for control-plane to be ready"
echo "-------------------------------------------------------------------"

echo "Waiting for control-plane pods to be ready..."
sleep 30
kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=300s || true

echo ""
echo "Step 5: Generate join command for workers"
echo "-------------------------------------------------------------------"

JOIN_COMMAND=$(kubeadm token create --print-join-command)
echo ""
echo "==================================================================="
echo "JOIN COMMAND FOR WORKERS:"
echo "==================================================================="
echo ""
echo "sudo $JOIN_COMMAND"
echo ""
echo "==================================================================="
echo ""
echo "Run the above command on each worker node to join the cluster."
echo ""
echo "After joining all workers, verify with:"
echo "  kubectl get nodes"
echo ""
echo "==================================================================="
